### PR TITLE
refactor paging query

### PR DESCRIPTION
**Pull request by tj-boyle**
- moving querybuild select to common function
- replace custom paging with built in paging
- fix total count

### CODE REVIEW

**Review by dallashuggins — COMMENTED** [review]
I've been seeing the following error when toggling the Purchase/Auction filters on the release page. Everything appears to be working though.
```
select "content" from "CmsCachePackTemplates" where "releasedAt" is null or "releasedAt" < $1 and "id" in ($2) order by "releasedAt" desc limit $3 - LIMIT must not be negative
```

**Review by smonn — APPROVED** [review]
I may not have enough packs in my local DB, but not seeing the error/warning @dallashuggins reported. Beyond that, code changes look good and work on my end.

**Comment by tj-boyle** [comment]
@dallashuggins I believe I just fixed that issue in my latest commit, let me know!

**Review by dallashuggins — APPROVED** [review]
🔥

**Comment by dallashuggins** [comment]
> @dallashuggins I believe I just fixed that issue in my latest commit, let me know!

@tj-boyle Sweet! That fixed it for me 🥳

**Pull request merged**
