### PR TITLE
Auction smart contract in PyTEAL

### LINKED ISSUE #209: Implement marketplace smart contract

### PR DESCRIPTION
**Pull request by smonn**
Closes #209 

Initial implementation of the auction smart contract. Includes built files in TEAL for convenience when used in the backend. With some slight tweaks, this is essentially the same as the [auction demo](https://github.com/algorand/auction-demo) contract. Reasoning being that we don't need a much more custom setup than that once we remove the default frozen option from our asset creation transaction.

### CODE REVIEW

**Review by jakerainis — APPROVED** [review]
Amazing work. I'd love to talk through a couple of logistics with you for strategy purposes, but this is a great start! :ship-it:

**Comment by smonn** [comment]
Also worth pointing out that this does not include any form of royalty mechanism. We'll also need to add a separate one if we want to support USDC as the currency (instead of ALGO).

**Review by davidjmurphyjr — APPROVED** [review]
I'm not proficient with any of this tech, but looks pretty good to me 👍

**Review by dallashuggins — APPROVED** [review]
Awesome! 🔥 I need to get more familiar with Python and smart contracts, but everything makes to my understanding.

**Pull request merged**
